### ISSUE TITLE
Question about number of parameters

### ISSUE THREAD

**Issue by hukkelas** [Vious/LBAM_Pytorch#6]
Hi,
I have a short question about how many parameters are in your network?
I  printed it with:
```python
print(sum([np.prod(_.shape) for _ in netG.parameters()]))
```
in test.py and got the number 68.3M parameters in the generator. Could you confirm that this is correct?

Thanks!

**Comment by Vious** [comment]
Thank you for your interest! Your are right, the netG.patamaters() are smaller than the saved *.pth file. It's because that I saved the model by netG.state_dict() which contains a dictionary of the module, not only parameters, but also some entries and running buffers. I guess its the reason why the size of .parameters() are far smaller than the saved state_dict file, I think the upload models are correct. If some error occurred in the testing phase, feel free to contact me :).

**Comment by hukkelas** [comment]
Thanks for the quick answer!
